global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ikyk-gateway'

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'management-api'
    static_configs:
      - targets: ['management-api:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s
